language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - pandoc

install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
#- pip install --upgrade pip setuptools wheel
#- pip install -r requirements.txt
#- gem install jekyll
#- gem install redcarpet
script:
- mkdir _site; echo "<head>Hello</head><body>Hello</body>" > _site/index.html # make
before_install:
- openssl aes-256-cbc -K $encrypted_194007bb00f1_key -iv $encrypted_194007bb00f1_iv
  -in deploy_key.enc -out deploy_key -d
- eval `ssh-agent -s`
- chmod 600 deploy_key
- ssh-add deploy_key
- rvm get stable --auto-dotfiles
- rvm install 2.3.1
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz | tar -JxC $HOME/texlive
after_success:
- git add -f _site
- git push -f -u origin gh-pages
