language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - pandoc

install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- tlmgr update --self
- tlmgr install adjustbox
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt
- gem install jekyll
- gem install redcarpet
script:
- make
before_install:
- openssl aes-256-cbc -K $encrypted_194007bb00f1_key -iv $encrypted_194007bb00f1_iv
  -in deploy_key.enc -out deploy_key -d
- rvm get stable --auto-dotfiles
- rvm install 2.3.1
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz | tar -JxC $HOME/texlive

after_success:
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- git add -f _site
- git push -f gh-pages
