language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - pandoc
      - ruby-dev
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - gem install jekyll
# command to run tests
script:
  - make
