contact: http://www.ucl.ac.uk/research-it-services/partner-with-us

title: "MPHYG001: Research Software Engineering With Python"
includeleftnav: True
short: MPHYG0001

defaults:
  - scope: {path: ""}
    values: {layout: default}

baseurl: /training/engineering

crumbs:
  - link: http://www.ucl.ac.uk/ISD
    text: ISD
  - link: http://www.ucl.ac.uk/isd/services
    text: OUR SERVICES
  - link: http://www.ucl.ac.uk/isd/services/research-it
    text: RESEARCH IT
  - link: http://www.ucl.ac.uk/isd/services/research-it/training
    text: TRAINING
  - link: http://development.rc.ucl.ac.uk/training
    text: MATERIALS

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]
